use intel_candidate_app::model::{
    CandidateClass, IntelCandidateHypothesisState, MarketContextStatus, ScoreBreakdown,
};

pub(crate) fn state() -> IntelCandidateHypothesisState {
    IntelCandidateHypothesisState {
        hypothesis_id: "hyp_001".to_owned(),
        state_key: "hypothesis-state/state.json".to_owned(),
        schema_version: "intel_candidate_hypothesis_state_v1".to_owned(),
        producer_app: "intel-candidate-app".to_owned(),
        producer_version: "0.1.0".to_owned(),
        created_at_ms: 1_000,
        updated_at_ms: 1_000,
        input_packet_id: "packet_001".to_owned(),
        input_packet_family_id: "family_001".to_owned(),
        input_packet_revision: 0,
        source_structured_packet_ids: vec!["packet_001".to_owned()],
        source_event_ids: vec!["source_001".to_owned()],
        supersedes_packet_id: None,
        supersedes_hypothesis_id: None,
        latest_screening_event_id: "screen_001".to_owned(),
        scoring_policy_version: "policy_v1".to_owned(),
        normalized_symbols: vec!["BTC".to_owned()],
        event_type: "funding_shift".to_owned(),
        hypothesis_type: "derivatives_pressure_shift".to_owned(),
        current_state: CandidateClass::WeakCandidate,
        current_score: 45,
        previous_score: None,
        research_eligible: false,
        transition: "created_or_refreshed".to_owned(),
        next_action: "rerun_when_market_feature_delta_updates".to_owned(),
        reasons: vec!["derivatives_metric_delta_missing".to_owned()],
        retryable_reasons: vec!["derivatives_metric_delta_missing".to_owned()],
        terminal_reasons: Vec::new(),
        selected_market_artifacts: Vec::new(),
        market_context_ref: None,
        market_context_status: MarketContextStatus::StaleButUsable,
        evidence_quality_reasons: Vec::new(),
        score_breakdown: ScoreBreakdown {
            components: Vec::new(),
            final_score: 45,
        },
        lineage_refs: vec!["packet_001".to_owned()],
        dirty_triggers: vec!["market_feature_delta_updated".to_owned()],
        harness_queue_hint: "derivatives_delta_persistence".to_owned(),
        idempotency_key: "idem_001".to_owned(),
        checksum: "checksum".to_owned(),
    }
}
